build:
  stage: build
  image: eclipse-temurin:8
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  before_script:
    - export DEBIAN_FRONTEND="noninteractive"
    - apt-get update
    - apt-get install --assume-yes maven
    - mvn --version
  script:
    - ./gradlew prepareMaven
    - mvn -Dmaven.repo.local="$CI_PROJECT_DIR/maven_repo_local" -f de.prob.parent/pom.xml install
    - cp footer.html de.prob.repository/target/repository/
  cache:
    paths:
      - .gradle/caches
      - .gradle/native
      - .gradle/wrapper
      - maven_repo_local
  artifacts:
    paths:
      - de.prob.repository/target/repository

deploy:nightly:
  stage: deploy
  only:
    - develop@general/stups/prob_rodin_plugin
  image: alpine:3
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk update
    - apk add lftp openssh-client
  script:
    - LFTP_PASSWORD="${DEPLOY_PASSWORD}" lftp -c "set cmd:fail-exit true; set sftp:auto-confirm true; open --user ${DEPLOY_USERNAME} --env-password sftp://${DEPLOY_HOST}/${DEPLOY_REMOTE_BASEDIR}/rodin/prob1/nightly/; mirror -vvv -R de.prob.repository/target/repository ."

deploy:release:
  stage: deploy
  only:
    - master@general/stups/prob_rodin_plugin
  image: alpine:3
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk update
    - apk add lftp openssh-client
  script:
    - LFTP_PASSWORD="${DEPLOY_PASSWORD}" lftp -c "set cmd:fail-exit true; set sftp:auto-confirm true; open --user ${DEPLOY_USERNAME} --env-password sftp://${DEPLOY_HOST}/${DEPLOY_REMOTE_BASEDIR}/rodin/prob1/; mkdir release-next; mirror -vvv -R de.prob.repository/target/repository release-next; mv release release-prev; mv release-next release"
