build:
  stage: build
  image: openjdk:8-jdk-slim
  before_script:
    - export DEBIAN_FRONTEND="noninteractive"
    - apt-get update
    - apt-get install --assume-yes maven
    - export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=192m"
    - mvn --version
  script:
    - ./gradlew createPoms
    - ./gradlew downloadCli
    - ./gradlew collectDependencies
    - mvn -f de.prob.parent/pom.xml install
    - ./gradlew collectArtifacts
  artifacts:
    paths:
      - updatesite

deploy:
  stage: deploy
  only:
    - develop@general/stups/prob_rodin_plugin
  image: $CI_REGISTRY/stups/prob/prob-docker/internal/deployment:0.7
  variables:
    DEPLOY_REMOTEDIR: "stupshome/stups/rodin/prob1/nightly"
  script:
    - travis-custom-deploy sftp updatesite/
