build:
  stage: build
  image: maven:3-eclipse-temurin-11
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  before_script:
    - mvn --version
  script:
    - ./gradlew --no-daemon --warning-mode=all prepareMaven
    - mvn -Dmaven.repo.local="$CI_PROJECT_DIR/maven_repo_local" -f de.prob.parent/pom.xml install
    - cp footer.html de.prob.repository/target/repository/
  cache:
    paths:
      - .gradle/caches
      - .gradle/native
      - .gradle/notifications
      - .gradle/wrapper
      - maven_repo_local
  artifacts:
    paths:
      - de.prob.repository/target/repository
      - "*/target/work/configuration/*.log"
    when: always

deploy:nightly:
  stage: deploy
  only:
    - develop@general/stups/prob_rodin_plugin
  image: alpine:3
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk update
    - apk add lftp openssh-client
  script:
    - LFTP_PASSWORD="${DEPLOY_PASSWORD}" lftp -c "set cmd:fail-exit true; set sftp:auto-confirm true; open --user ${DEPLOY_USERNAME} --env-password sftp://${DEPLOY_HOST}/${DEPLOY_REMOTE_BASEDIR}/rodin/prob1/nightly/; mirror -vvv -R --delete de.prob.repository/target/repository ."

deploy:release:
  stage: deploy
  only:
    - master@general/stups/prob_rodin_plugin
  image: alpine:3
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk update
    - apk add lftp openssh-client
  script:
    - LFTP_PASSWORD="${DEPLOY_PASSWORD}" lftp -c "set cmd:fail-exit true; set sftp:auto-confirm true; open --user ${DEPLOY_USERNAME} --env-password sftp://${DEPLOY_HOST}/${DEPLOY_REMOTE_BASEDIR}/rodin/prob1/; mkdir release-next; mirror -vvv -R de.prob.repository/target/repository release-next; mv release release-prev; mv release-next release"
