build:
  stage: build
  image: openjdk:8-jdk-slim
  before_script:
    - export DEBIAN_FRONTEND="noninteractive"
    - apt-get update
    # perl provides shasum
    - apt-get install --assume-yes curl perl
    - curl --location -o apache-maven-3.6.3-bin.tar.gz https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
    - shasum --algorithm 512 --quiet --check - <<< "c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0 *apache-maven-3.6.3-bin.tar.gz"
    - tar -zxvf apache-maven-3.6.3-bin.tar.gz
    - export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=192m"
    - export M2_HOME=$PWD/apache-maven-3.6.3
    - export PATH=$M2_HOME/bin:$PATH
    - mvn --version
  script:
    - ./gradlew createPoms
    - ./gradlew downloadCli
    - ./gradlew collectDependencies
    - mvn -f de.prob.parent/pom.xml install
    - ./gradlew collectArtifacts
  artifacts:
    paths:
      - updatesite

deploy:
  stage: deploy
  only:
    - develop@general/stups/prob_rodin_plugin
  image: $CI_REGISTRY/stups/prob/prob-docker/internal/deployment:0.7
  variables:
    DEPLOY_REMOTEDIR: "stupshome/stups/rodin/prob1/nightly"
  script:
    - travis-custom-deploy sftp updatesite/
