build:
  stage: build
  image: openjdk:8-jdk-slim
  before_script:
    - export DEBIAN_FRONTEND="noninteractive"
    - apt-get update
    # perl provides shasum
    - apt-get install --assume-yes curl perl
    - curl --location -o apache-maven-3.5.4-bin.tar.gz https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
    - md5sum --quiet --check - <<< "89eea39183139e5f8a0c1601d495b3b6 *apache-maven-3.5.4-bin.tar.gz"
    - shasum --algorithm 1 --quiet --check - <<< "22cac91b3557586bb1eba326f2f7727543ff15e3 *apache-maven-3.5.4-bin.tar.gz"
    - shasum --algorithm 256 --quiet --check - <<< "ce50b1c91364cb77efe3776f756a6d92b76d9038b0a0782f7d53acf1e997a14d *apache-maven-3.5.4-bin.tar.gz"
    - shasum --algorithm 512 --quiet --check - <<< "2a803f578f341e164f6753e410413d16ab60fabe31dc491d1fe35c984a5cce696bc71f57757d4538fe7738be04065a216f3ebad4ef7e0ce1bb4c51bc36d6be86 *apache-maven-3.5.4-bin.tar.gz"
    - tar -zxvf apache-maven-3.5.4-bin.tar.gz
    - export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=192m"
    - export M2_HOME=$PWD/apache-maven-3.5.4
    - export PATH=$M2_HOME/bin:$PATH
    - mvn --version
  script:
    - ./gradlew createPoms
    - ./gradlew downloadCli
    - ./gradlew collectDependencies
    - mvn -f de.prob.parent/pom.xml install
    - ./gradlew collectArtifacts
  artifacts:
    paths:
      - updatesite

deploy:
  stage: deploy
  only:
    - develop@general/stups/prob_rodin_plugin
  image: $CI_REGISTRY/stups/prob/prob-docker/internal/deployment:0.7
  variables:
    DEPLOY_REMOTEDIR: "stupshome/stups/rodin/prob1/nightly"
  script:
    - travis-custom-deploy sftp updatesite/
